# Generated by Django 3.2 on 2021-04-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='data de compra')),
                ('preco_total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='compra_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.compra'),
        ),
    ]
