# Generated by Django 3.2 on 2021-04-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210415_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_compra',
            field=models.IntegerField(default=1),
        ),
    ]
