# Generated by Django 3.2 on 2021-04-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210420_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='compra',
            field=models.ManyToManyField(blank=True, null=True, to='store.Compra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.ManyToManyField(blank=True, null=True, to='store.Tamanho'),
        ),
    ]
