# Generated by Django 3.2 on 2021-04-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_produto_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantidade_total',
        ),
    ]
