# Generated by Django 3.2 on 2021-04-21 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cliente'),
        ),
    ]
