# Generated by Django 3.2 on 2021-04-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_compra_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de compra'),
        ),
    ]
