# Generated by Django 3.2 on 2021-04-21 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_compra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='data compra'),
        ),
    ]
