# Generated by Django 3.2 on 2021-04-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_itemscompra_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao_grande',
            field=models.CharField(default='', max_length=200),
        ),
    ]
